'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ModuleQuotation

    '''<summary>
    '''gv_QuotationDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_QuotationDescription As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''DataSource_QuotationDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DataSource_QuotationDescription As Global.System.Web.UI.WebControls.SqlDataSource
End Class
