'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ProposalUpload

    '''<summary>
    '''lbl_PNewUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_PNewUpload As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lbl_PNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_PNo As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Updatepanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Updatepanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdate As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''ulc_ProposalFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ulc_ProposalFile As Global.DevExpress.Web.ASPxUploadControl.ASPxUploadControl

    '''<summary>
    '''lbl_ProposalNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ProposalNumber As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lbl_PCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_PCompanyName As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''gv_PFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_PFile As Global.DevExpress.Web.ASPxGridView.ASPxGridView
End Class
