'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SearchDocument

    '''<summary>
    '''AddNewDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddNewDocument As Global.Bonzen_DLMS.AddNewDocument

    '''<summary>
    '''pop_PreviewQuotation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pop_PreviewQuotation As Global.DevExpress.Web.ASPxPopupControl.ASPxPopupControl

    '''<summary>
    '''cbp_PreviewQuotation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbp_PreviewQuotation As Global.DevExpress.Web.ASPxCallbackPanel.ASPxCallbackPanel

    '''<summary>
    '''lbl_QNewUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_QNewUpload As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lbl_QNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_QNo As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lbl_QuotationNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_QuotationNumber As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lbl_QCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_QCompanyName As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''gv_QFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_QFile As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''lbl_Total control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Total As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lbl_QTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_QTotal As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lbl_Remark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Remark As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lbl_QRemarke control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_QRemarke As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''gv_quotationProposal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_quotationProposal As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''Quo_Prop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Quo_Prop As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''gv_general control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_general As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''General control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents General As Global.System.Web.UI.WebControls.SqlDataSource
End Class
