'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SearchDocument

    '''<summary>
    '''AddNewDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddNewDocument As Global.Bonzen_DLMS.AddNewDocument

    '''<summary>
    '''gv_quotationProposal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_quotationProposal As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''Quo_Prop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Quo_Prop As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''gv_general control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_general As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''General control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents General As Global.System.Web.UI.WebControls.SqlDataSource
End Class
