'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddNewDocument

    '''<summary>
    '''btn_AddDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_AddDocument As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''pop_AddDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pop_AddDocument As Global.DevExpress.Web.ASPxPopupControl.ASPxPopupControl

    '''<summary>
    '''lbl_DocumentType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_DocumentType As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmb_DocumentType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmb_DocumentType As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''cb_PopupInit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_PopupInit As Global.DevExpress.Web.ASPxCallback.ASPxCallback

    '''<summary>
    '''pop_quotation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pop_quotation As Global.DevExpress.Web.ASPxPopupControl.ASPxPopupControl

    '''<summary>
    '''lbl_Q control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Q As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lbl_QNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_QNo As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lbl_QTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_QTitle As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtb_QTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtb_QTitle As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lbl_QDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_QDate As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Q_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Q_Date As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''lbl_QBookBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_QBookBy As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lbl_QName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_QName As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lbl_Validate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Validate As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''btnQ_OK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnQ_OK As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btnQ_Cencel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnQ_Cencel As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''pop_proposal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pop_proposal As Global.DevExpress.Web.ASPxPopupControl.ASPxPopupControl

    '''<summary>
    '''lbl_QNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_QNum As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cbb_QId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbb_QId As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''sds_Quotation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_Quotation As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lbl_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_P As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lbl_PNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_PNo As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lbl_ErrorProp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ErrorProp As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''btn_POK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_POK As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btn_PCencel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_PCencel As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''pop_general control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pop_general As Global.DevExpress.Web.ASPxPopupControl.ASPxPopupControl

    '''<summary>
    '''lbl_G control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_G As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lbl_GNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_GNo As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lbl_company control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_company As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmb_company control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmb_company As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lds_Company control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lds_Company As Global.System.Web.UI.WebControls.LinqDataSource

    '''<summary>
    '''lbl_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_name As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmb_attn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmb_attn As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lds_Attn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lds_Attn As Global.System.Web.UI.WebControls.LinqDataSource

    '''<summary>
    '''lbl_GTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_GTitle As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtb_GTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtb_GTitle As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lbl_GDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_GDate As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''G_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents G_Date As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''lbl_GBookBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_GBookBy As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lbl_GName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_GName As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lbl_ErrorGen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ErrorGen As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''btn_GOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_GOK As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btn_GCencel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_GCencel As Global.DevExpress.Web.ASPxEditors.ASPxButton
End Class
